# Generated by Django 6.1 on 2026-08-07 06:56

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('authority', models.CharField(blank=True, max_length=255)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('ia_prefix', models.CharField(blank=True, max_length=128)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('gazette_count', models.PositiveIntegerField(default=0)),
                ('earliest_date', models.DateField(blank=True, null=True)),
                ('latest_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Gazette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255, unique=True)),
                ('relurl', models.CharField(max_length=512, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('title', models.TextField()),
                ('subject', models.TextField(blank=True)),
                ('gznum', models.CharField(blank=True, max_length=255)),
                ('gztype', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=512)),
                ('ministry', models.CharField(blank=True, max_length=512)),
                ('office', models.CharField(blank=True, max_length=512)),
                ('partnum', models.CharField(blank=True, max_length=255)),
                ('notification_num', models.CharField(blank=True, max_length=255)),
                ('refnum', models.CharField(blank=True, max_length=255)),
                ('source_url', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('text', models.TextField(blank=True)),
                ('text_truncated', models.BooleanField(default=False)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('has_pymupdf', models.BooleanField(default=False)),
                ('has_pdf', models.BooleanField(default=False)),
                ('pdf_bytes', models.BigIntegerField(blank=True, null=True)),
                ('html_sha256', models.CharField(blank=True, max_length=64)),
                ('metadata_sha256', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gazettes', to='gazettes.source')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='gazette_search_gin'), models.Index(fields=['-date'], name='gazette_date_desc'), models.Index(fields=['source', '-date'], name='gazette_source_date'), models.Index(fields=['year'], name='gazette_year')],
            },
        ),
    ]
