locality = {\
'AL': 'alabama', \
'AK': 'alaska', \
'AZ': 'arizona', \
'AR': 'arkansas', \
'CA': 'california', \
'CO': 'colorado', \
'CT': 'connecticut', \
'DE': 'delaware', \
'FL': 'florida', \
'GA': 'georgia', \
'HI': 'hawaii', \
'ID': 'idaho', \
'IL': 'illinois', \
'IN': 'indiana', \
'IA': 'iowa', \
'KS': 'kansas', \
'KY': 'kentucky', \
'LA': 'louisiana', \
'ME': 'maine', \
'MD': 'maryland', \
'MA': 'massachusetts', \
'MI': 'michigan', \
'MN': 'minnesota', \
'MS': 'mississippi', \
'MO': 'missouri', \
'MT': 'montana', \
'NE': 'nebraska', \
'NV': 'nevada', \
'NH': 'newhampshire', \
'NJ': 'newjersey', \
'NM': 'newmexico', \
'NY': 'newyork', \
'NC': 'northcarolina', \
'ND': 'northdakota', \
'OH': 'ohio', \
'OK': 'oklahoma', \
'OR': 'oregon', \
'PA': 'pennsylvania', \
'RI': 'rhodeisland', \
'SC': 'southcarolina', \
'SD': 'southdakota', \
'TN': 'tennessee', \
'TX': 'texas', \
'UT': 'utah', \
'VT': 'vermont', \
'VA': 'virginia', \
'WA': 'washington', \
'WV': 'westvirginia', \
'WI': 'wisconsin', \
'WY': 'wyoming', \
}

start_year = {
'MI': '1970', \
'CA': '1988', \
'FL': '1974', \
'GA': '1946'  \
}
