locality = {\
'AL': 'alabama', \
'AK': 'alaska', \
'AZ': 'arizona', \
'AR': 'arkansas', \
'CA': 'california', \
'CO': 'colorado', \
'CT': 'connecticut', \
'DE': 'delaware', \
'FL': 'florida', \
'GA': 'georgia', \
'HI': 'hawaii', \
'ID': 'idaho', \
'IL': 'illinois', \
'IN': 'indiana', \
'IA': 'iowa', \
'KS': 'kansas', \
'KY': 'kentucky', \
'LA': 'louisiana', \
'ME': 'maine', \
'MD': 'maryland', \
'MA': 'massachusetts', \
'MI': 'michigan', \
'MN': 'minnesota', \
'MS': 'mississippi', \
'MO': 'missouri', \
'MT': 'montana', \
'NE': 'nebraska', \
'NV': 'nevada', \
'NH': 'newhampshire', \
'NJ': 'newjersey', \
'NM': 'newmexico', \
'NY': 'newyork', \
'NC': 'northcarolina', \
'ND': 'northdakota', \
'OH': 'ohio', \
'OK': 'oklahoma', \
'OR': 'oregon', \
'PA': 'pennsylvania', \
'RI': 'rhodeisland', \
'SC': 'southcarolina', \
'SD': 'southdakota', \
'TN': 'tennessee', \
'TX': 'texas', \
'UT': 'utah', \
'VT': 'vermont', \
'VA': 'virginia', \
'WA': 'washington', \
'WV': 'westvirginia', \
'WI': 'wisconsin', \
'WY': 'wyoming', \
}

start_year = {
'MI': '1970', \
'CA': '1988', \
'FL': '1974', \
'PA': '1968', \
'NY': '1909', \
'WI': '1957', \
'NV': '1977', \
'TN': '1974', \
'IL': '1978', \
'NC': '1986', \
'SC': '1976', \
'OH': '1977', \
'TX': '1977', \
'GA': '1946',  \
'AL': '1981', \
'AK': '1967', \
'AR': '1967', \
'AZ': '1952', \
'CO': '1959', \
'CT': '1945', \
'DE': '1960', \
'HI': '1961', \
'IA': '1975', \
'ID': '1965', \
'IN': '1986', \
'KS': '1984', \
'KY': '1984', \
'LA': '1966', \
'MA': '1954', \
'MD': '1957', \
'ME': '1961', \
'MN': '1946', \
'MO': '1945', \
'MS': '1976', \
'MT': '1971', \
}

title_states = set(['GA', 'WI', 'NV', 'CA', 'PA', 'NY', 'IL', 'NC', 'SC', 'TX', 'OH', 'TN', 'AK', 'AR', 'AL', 'AZ', 'CT', 'CO', 'DE', 'HI', 'IA', 'ID', 'IN', 'KS', 'KY'])

